package ibgo

const (
	inTICKPRICE                            = "1"
	inTICKSIZE                             = "2"
	inORDERSTATUS                          = "3"
	inERRMSG                               = "4"
	inOPENORDER                            = "5"
	inACCTVALUE                            = "6"
	inPORTFOLIOVALUE                       = "7"
	inACCTUPDATETIME                       = "8"
	inNEXTVALIDID                          = "9"
	inCONTRACTDATA                         = "10"
	inEXECUTIONDATA                        = "11"
	inMARKETDEPTH                          = "12"
	inMARKETDEPTHL2                        = "13"
	inNEWSBULLETINS                        = "14"
	inMANAGEDACCTS                         = "15"
	inRECEIVEFA                            = "16"
	inHISTORICALDATA                       = "17"
	inBONDCONTRACTDATA                     = "18"
	inSCANNERPARAMETERS                    = "19"
	inSCANNERDATA                          = "20"
	inTICKOPTIONCOMPUTATION                = "21"
	inTICKGENERIC                          = "45"
	inTICKSTRING                           = "46"
	inTICKEFP                              = "47"
	inCURRENTTIME                          = "49"
	inREALTIMEBARS                         = "50"
	inFUNDAMENTALDATA                      = "51"
	inCONTRACTDATAEND                      = "52"
	inOPENORDEREND                         = "53"
	inACCTDOWNLOADEND                      = "54"
	inEXECUTIONDATAEND                     = "55"
	inDELTANEUTRALVALIDATION               = "56"
	inTICKSNAPSHOTEND                      = "57"
	inMARKETDATATYPE                       = "58"
	inCOMMISSIONREPORT                     = "59"
	inPOSITIONDATA                         = "61"
	inPOSITIONEND                          = "62"
	inACCOUNTSUMMARY                       = "63"
	inACCOUNTSUMMARYEND                    = "64"
	inVERIFYMESSAGEAPI                     = "65"
	inVERIFYCOMPLETED                      = "66"
	inDISPLAYGROUPLIST                     = "67"
	inDISPLAYGROUPUPDATED                  = "68"
	inVERIFYANDAUTHMESSAGEAPI              = "69"
	inVERIFYANDAUTHCOMPLETED               = "70"
	inPOSITIONMULTI                        = "71"
	inPOSITIONMULTIEND                     = "72"
	inACCOUNTUPDATEMULTI                   = "73"
	inACCOUNTUPDATEMULTIEND                = "74"
	inSECURITYDEFINITIONOPTIONPARAMETER    = "75"
	inSECURITYDEFINITIONOPTIONPARAMETEREND = "76"
	inSOFTDOLLARTIERS                      = "77"
	inFAMILYCODES                          = "78"
	inSYMBOLSAMPLES                        = "79"
	inMKTDEPTHEXCHANGES                    = "80"
	inTICKREQPARAMS                        = "81"
	inSMARTCOMPONENTS                      = "82"
	inNEWSARTICLE                          = "83"
	inTICKNEWS                             = "84"
	inNEWSPROVIDERS                        = "85"
	inHISTORICALNEWS                       = "86"
	inHISTORICALNEWSEND                    = "87"
	inHEADTIMESTAMP                        = "88"
	inHISTOGRAMDATA                        = "89"
	inHISTORICALDATAUPDATE                 = "90"
	inREROUTEMKTDATAREQ                    = "91"
	inREROUTEMKTDEPTHREQ                   = "92"
	inMARKETRULE                           = "93"
	inPNL                                  = "94"
	inPNLSINGLE                            = "95"
	inHISTORICALTICKS                      = "96"
	inHISTORICALTICKSBIDASK                = "97"
	inHISTORICALTICKSLAST                  = "98"
	inTICKBYTICK                           = "99"
	inORDERBOUND                           = "100"
	inCOMPLETEDORDER                       = "101"
	inCOMPLETEDORDERSEND                   = "102"
	inREPLACEFAEND                         = "103"
)

const (
	outREQMKTDATA                 = "1"
	outCANCELMKTDATA              = "2"
	outPLACEORDER                 = "3"
	outCANCELORDER                = "4"
	outREQOPENORDERS              = "5"
	outREQACCTDATA                = "6"
	outREQEXECUTIONS              = "7"
	outREQIDS                     = "8"
	outREQCONTRACTDATA            = "9"
	outREQMKTDEPTH                = "10"
	outCANCELMKTDEPTH             = "11"
	outREQNEWSBULLETINS           = "12"
	outCANCELNEWSBULLETINS        = "13"
	outSETSERVERLOGLEVEL          = "14"
	outREQAUTOOPENORDERS          = "15"
	outREQALLOPENORDERS           = "16"
	outREQMANAGEDACCTS            = "17"
	outREQFA                      = "18"
	outREPLACEFA                  = "19"
	outREQHISTORICALDATA          = "20"
	outEXERCISEOPTIONS            = "21"
	outREQSCANNERSUBSCRIPTION     = "22"
	outCANCELSCANNERSUBSCRIPTION  = "23"
	outREQSCANNERPARAMETERS       = "24"
	outCANCELHISTORICALDATA       = "25"
	outREQCURRENTTIME             = "49"
	outREQREALTIMEBARS            = "50"
	outCANCELREALTIMEBARS         = "51"
	outREQFUNDAMENTALDATA         = "52"
	outCANCELFUNDAMENTALDATA      = "53"
	outREQCALCIMPLIEDVOLAT        = "54"
	outREQCALCOPTIONPRICE         = "55"
	outCANCELCALCIMPLIEDVOLAT     = "56"
	outCANCELCALCOPTIONPRICE      = "57"
	outREQGLOBALCANCEL            = "58"
	outREQMARKETDATATYPE          = "59"
	outREQPOSITIONS               = "61"
	outREQACCOUNTSUMMARY          = "62"
	outCANCELACCOUNTSUMMARY       = "63"
	outCANCELPOSITIONS            = "64"
	outVERIFYREQUEST              = "65"
	outVERIFYMESSAGE              = "66"
	outQUERYDISPLAYGROUPS         = "67"
	outSUBSCRIBETOGROUPEVENTS     = "68"
	outUPDATEDISPLAYGROUP         = "69"
	outUNSUBSCRIBEFROMGROUPEVENTS = "70"
	outSTARTAPI                   = "71"
	outVERIFYANDAUTHREQUEST       = "72"
	outVERIFYANDAUTHMESSAGE       = "73"
	outREQPOSITIONSMULTI          = "74"
	outCANCELPOSITIONSMULTI       = "75"
	outREQACCOUNTUPDATESMULTI     = "76"
	outCANCELACCOUNTUPDATESMULTI  = "77"
	outREQSECDEFOPTPARAMS         = "78"
	outREQSOFTDOLLARTIERS         = "79"
	outREQFAMILYCODES             = "80"
	outREQMATCHINGSYMBOLS         = "81"
	outREQMKTDEPTHEXCHANGES       = "82"
	outREQSMARTCOMPONENTS         = "83"
	outREQNEWSARTICLE             = "84"
	outREQNEWSPROVIDERS           = "85"
	outREQHISTORICALNEWS          = "86"
	outREQHEADTIMESTAMP           = "87"
	outREQHISTOGRAMDATA           = "88"
	outCANCELHISTOGRAMDATA        = "89"
	outCANCELHEADTIMESTAMP        = "90"
	outREQMARKETRULE              = "91"
	outREQPNL                     = "92"
	outCANCELPNL                  = "93"
	outREQPNLSINGLE               = "94"
	outCANCELPNLSINGLE            = "95"
	outREQHISTORICALTICKS         = "96"
	outREQTICKBYTICKDATA          = "97"
	outCANCELTICKBYTICKDATA       = "98"
	outREQCOMPLETEDORDERS         = "99"
)

// server version
const (
	// mMINSERVERVERREALTIMEBARS       = 34
	// mMINSERVERVERSCALEORDERS         = 35
	// mMINSERVERVERSNAPSHOTMKTDATA    = 35
	// mMINSERVERVERSSHORTCOMBOLEGS    = 35
	// mMINSERVERVERWHATIFORDERS       = 36
	// mMINSERVERVERCONTRACTCONID       = 37
	vMINSERVERVERPTAORDERS               int64 = 39
	vMINSERVERVERFUNDAMENTALDATA         int64 = 40
	vMINSERVERVERDELTANEUTRAL            int64 = 40
	vMINSERVERVERCONTRACTDATACHAIN       int64 = 40
	vMINSERVERVERSCALEORDERS2            int64 = 40
	vMINSERVERVERALGOORDERS              int64 = 41
	vMINSERVERVEREXECUTIONDATACHAIN      int64 = 42
	vMINSERVERVERNOTHELD                 int64 = 44
	vMINSERVERVERSECIDTYPE               int64 = 45
	vMINSERVERVERPLACEORDERCONID         int64 = 46
	vMINSERVERVERREQMKTDATACONID         int64 = 47
	vMINSERVERVERREQCALCIMPLIEDVOLAT     int64 = 49
	vMINSERVERVERREQCALCOPTIONPRICE      int64 = 50
	vMINSERVERVERSSHORTXOLD              int64 = 51
	vMINSERVERVERSSHORTX                 int64 = 52
	vMINSERVERVERREQGLOBALCANCEL         int64 = 53
	vMINSERVERVERHEDGEORDERS             int64 = 54
	vMINSERVERVERREQMARKETDATATYPE       int64 = 55
	vMINSERVERVEROPTOUTSMARTROUTING      int64 = 56
	vMINSERVERVERSMARTCOMBOROUTINGPARAMS int64 = 57
	vMINSERVERVERDELTANEUTRALCONID       int64 = 58
	vMINSERVERVERSCALEORDERS3            int64 = 60
	vMINSERVERVERORDERCOMBOLEGSPRICE     int64 = 61
	vMINSERVERVERTRAILINGPERCENT         int64 = 62
	vMINSERVERVERDELTANEUTRALOPENCLOSE   int64 = 66
	vMINSERVERVERPOSITIONS               int64 = 67
	vMINSERVERVERACCOUNTSUMMARY          int64 = 67
	vMINSERVERVERTRADINGCLASS            int64 = 68
	vMINSERVERVERSCALETABLE              int64 = 69
	vMINSERVERVERLINKING                 int64 = 70
	vMINSERVERVERALGOID                  int64 = 71
	vMINSERVERVEROPTIONALCAPABILITIES    int64 = 72
	vMINSERVERVERORDERSOLICITED          int64 = 73
	vMINSERVERVERLINKINGAUTH             int64 = 74
	vMINSERVERVERPRIMARYEXCH             int64 = 75
	vMINSERVERVERRANDOMIZESIZEANDPRICE   int64 = 76
	vMINSERVERVERFRACTIONALPOSITIONS     int64 = 101
	vMINSERVERVERPEGGEDTOBENCHMARK       int64 = 102
	vMINSERVERVERMODELSSUPPORT           int64 = 103
	vMINSERVERVERSECDEFOPTPARAMSREQ      int64 = 104
	vMINSERVERVEREXTOPERATOR             int64 = 105
	vMINSERVERVERSOFTDOLLARTIER          int64 = 106
	vMINSERVERVERREQFAMILYCODES          int64 = 107
	vMINSERVERVERREQMATCHINGSYMBOLS      int64 = 108
	vMINSERVERVERPASTLIMIT               int64 = 109
	vMINSERVERVERMDSIZEMULTIPLIER        int64 = 110
	vMINSERVERVERCASHQTY                 int64 = 111
	vMINSERVERVERREQMKTDEPTHEXCHANGES    int64 = 112
	vMINSERVERVERTICKNEWS                int64 = 113
	vMINSERVERVERREQSMARTCOMPONENTS      int64 = 114
	vMINSERVERVERREQNEWSPROVIDERS        int64 = 115
	vMINSERVERVERREQNEWSARTICLE          int64 = 116
	vMINSERVERVERREQHISTORICALNEWS       int64 = 117
	vMINSERVERVERREQHEADTIMESTAMP        int64 = 118
	vMINSERVERVERREQHISTOGRAM            int64 = 119
	vMINSERVERVERSERVICEDATATYPE         int64 = 120
	vMINSERVERVERAGGGROUP                int64 = 121
	vMINSERVERVERUNDERLYINGINFO          int64 = 122
	vMINSERVERVERCANCELHEADTIMESTAMP     int64 = 123
	vMINSERVERVERSYNTREALTIMEBARS        int64 = 124
	vMINSERVERVERCFDRERINE               int64 = 125
	vMINSERVERVERMARKETRULES             int64 = 126
	vMINSERVERVERPNL                     int64 = 127
	vMINSERVERVERNEWSQUERYORIGINS        int64 = 128
	vMINSERVERVERUNREALIZEDPNL           int64 = 129
	vMINSERVERVERHISTORICALTICKS         int64 = 130
	vMINSERVERVERMARKETCAPPRICE          int64 = 131
	vMINSERVERVERPREOPENBIDASK           int64 = 132
	vMINSERVERVERREALEXPIRATIONDATE      int64 = 134
	vMINSERVERVERREALIZEDPNL             int64 = 135
	vMINSERVERVERLASTLIQUIDITY           int64 = 136
	vMINSERVERVERTICKBYTICK              int64 = 137
	vMINSERVERVERDECISIONMAKER           int64 = 138
	vMINSERVERVERMIFIDEXECUTION          int64 = 139
	vMINSERVERVERTICKBYTICKIGNORESIZE    int64 = 140
	vMINSERVERVERAUTOPRICEFORHEDGE       int64 = 141
	vMINSERVERVERWHATIFEXTFIELDS         int64 = 142
	vMINSERVERVERSCANNERGENERICOPTS      int64 = 143
	vMINSERVERVERAPIBINDORDER            int64 = 144
	vMINSERVERVERORDERCONTAINER          int64 = 145
	vMINSERVERVERSMARTDEPTH              int64 = 146
	vMINSERVERVERREMOVENULLALLCASTING    int64 = 147
	vMINSERVERVERDPEGORDERS              int64 = 148
	vMINSERVERVERMKTDEPTHPRIMEXCHANGE    int64 = 149
	vMINSERVERVERCOMPLETEDORDERS         int64 = 150
	vMINSERVERVERPRICEMGMTALGO           int64 = 151
	vMINSERVERVERSTOCKTYPE               int64 = 152
	vMINSERVERVERENCODEMSGASCII7         int64 = 153
	vMINSERVERVERSENDALLFAMILYCODES      int64 = 154
	vMINSERVERVERNODEFAULTOPENCLOSE      int64 = 155
	vMINSERVERVERREPLACEFAEND            int64 = 157

	MINCLIENTVER int64 = 100
	MAXCLIENTVER int64 = vMINSERVERVERREPLACEFAEND
)

// tick const
const (
	BIDSIZE = iota
	BID
	ASK
	ASKSIZE
	LAST
	LASTSIZE
	HIGH
	LOW
	VOLUME
	CLOSE
	BIDOPTIONCOMPUTATION
	ASKOPTIONCOMPUTATION
	LASTOPTIONCOMPUTATION
	MODELOPTION
	OPEN
	LOW13WEEK
	HIGH13WEEK
	LOW26WEEK
	HIGH26WEEK
	LOW52WEEK
	HIGH52WEEK
	AVGVOLUME
	OPENINTEREST
	OPTIONHISTORICALVOL
	OPTIONIMPLIEDVOL
	OPTIONBIDEXCH
	OPTIONASKEXCH
	OPTIONCALLOPENINTEREST
	OPTIONPUTOPENINTEREST
	OPTIONCALLVOLUME
	OPTIONPUTVOLUME
	INDEXFUTUREPREMIUM
	BIDEXCH
	ASKEXCH
	AUCTIONVOLUME
	AUCTIONPRICE
	AUCTIONIMBALANCE
	MARKPRICE
	BIDEFPCOMPUTATION
	ASKEFPCOMPUTATION
	LASTEFPCOMPUTATION
	OPENEFPCOMPUTATION
	HIGHEFPCOMPUTATION
	LOWEFPCOMPUTATION
	CLOSEEFPCOMPUTATION
	LASTTIMESTAMP
	SHORTABLE
	FUNDAMENTALRATIOS
	RTVOLUME
	HALTED
	BIDYIELD
	ASKYIELD
	LASTYIELD
	CUSTOPTIONCOMPUTATION
	TRADECOUNT
	TRADERATE
	VOLUMERATE
	LASTRTHTRADE
	RTHISTORICALVOL
	IBDIVIDENDS
	BONDFACTORMULTIPLIER
	REGULATORYIMBALANCE
	NEWSTICK
	SHORTTERMVOLUME3MIN
	SHORTTERMVOLUME5MIN
	SHORTTERMVOLUME10MIN
	DELAYEDBID
	DELAYEDASK
	DELAYEDLAST
	DELAYEDBIDSIZE
	DELAYEDASKSIZE
	DELAYEDLASTSIZE
	DELAYEDHIGH
	DELAYEDLOW
	DELAYEDVOLUME
	DELAYEDCLOSE
	DELAYEDOPEN
	RTTRDVOLUME
	CREDITMANMARKPRICE
	CREDITMANSLOWMARKPRICE
	DELAYEDBIDOPTION
	DELAYEDASKOPTION
	DELAYEDLASTOPTION
	DELAYEDMODELOPTION
	LASTEXCH
	LASTREGTIME
	FUTURESOPENINTEREST
	AVGOPTVOLUME
	DELAYEDLASTTIMESTAMP
	SHORTABLESHARES
	NOTSET
)
